/**
 * Word Laboratory engine — public surface.
 *
 * The engine is framework-agnostic pure TypeScript: no React, no DOM, no network.
 * That keeps the meaning-first pipeline testable in isolation and ready to be
 * driven later by an LLM or an interactive "Word Genome" slider UI.
 */
export * from './types'
export { runLaboratory, generateFamilies, generateWords, buildPassport, discoverFromAnalysis } from './generator'
export { analyzeMeaning, matchTheme, focusConcepts, dampenAttractors } from './meaning'
export { METAMORPHOSIS_CUE } from './attractors'
export { detectTargetType, targetTypeMatch } from './target-type'
export { THEMES } from './data/themes'
export { buildConceptMap, topConcepts, conceptMatch } from './concepts'
export { computeGenome, genomeQuality, estimateUniqueness, editDistance } from './genome'
export { computeEmotionalDNA, dominantEmotions } from './emotional'
export { matchBrands } from './brand'
export { ratePronunciation } from './pronunciation'
export { assessAdoption } from './adoption'
export { evolveWord, EVOLVE_DIRECTIONS } from './evolve'
export type { EvolveDirection, WordEvolutionStep } from './evolve'
export { speakNative, DEFAULT_SPEAKABILITY } from './synth'
export { speakabilityBand, longestVowelRun, pronounceability } from './phonetics'
export { offlineCollision, buildCollisionReport } from './collision'
export { naturalness, naturalnessBand, EXCEPTIONAL_NATURALNESS } from './naturalness'
export type { NaturalnessBand } from './naturalness'
export { computeFitness, SURVIVOR_FLOOR } from './fitness'
export { computeDictionaryViability } from './dictionary-viability'
export { computeBrandSafety } from './brand-safety'
export { computeDiscovery, NEUTRAL_ACOUSTIC } from './lexical-score'
export { computeParadigm } from './morphology'
export { computeEtymology } from './etymology'
export { computePhonology, observedProfile } from './phonology'
export { computeSemanticNetwork } from './network'
export { acousticProfile, conceptAcoustic, blendAcoustic } from './acoustics'
export { computeLanguageGenome, computeWordEvolution } from './language'
export { pronounce } from './pronounce'
export { translitRu } from './translit'
export { LANGUAGES, languageById } from './data/languages'
export type { Language } from './data/languages'
export { MODES, DEFAULT_MODE } from './data/modes'
export type { ModeProfile } from './data/modes'
export { IDEAS } from './data/ideas'
export { Rng, hashSeed } from './rng'
